if: tag IS blank

sudo: false
dist: trusty

language: node_js
node_js:
  - '12'

git:
  depth: 1

addons:
  apt:
    packages:
    - curl
    update: true

install:
  - curl --version

script:
  - ":"
  